name: Exec Benchmark

on:
  workflow_dispatch:
    inputs:
      cloud_provider:
        default: aws-cn
        required: true
        type: string
      region:
        default: cn-northwest-1
        required: true
        type: string
      uninstall:
        default: false
        required: true
        type: boolean


jobs:
  prepare_env:
    name: Prepare AWS Environment
    runs-on: ubuntu-latest
    environment:  ${{ inputs.cloud_provider }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2        

      - name: Build Benchmark Code
        run: |
          mvn clean package -Dlicense.skip=true -Dcheckstyle.skip -DskipTests -Dspotless.check.skip

      - name: Apply Variables and Secrets
        working-directory: driver-automq/deploy/terraform-aws
        ## Set AK/SK and terraform s3 backend info
        run: |
          echo "current path is: $(pwd)"
           ls -l provision-kafka-aws.tf
          sed -i "s/TF_BACKEND_BUCKET/$TF_BACKEND_BUCKET/g" "$TF_FILENAME"
          TF_FILENAME=$TF_FILENAME
          sed -i "s/TF_BACKEND_KEY/$TF_BACKEND_KEY/g" "$TF_FILENAME"
          sed -i "s/TF_BACKEND_REGION/${{ inputs.region }}/g" "$TF_FILENAME"
          sed -i "s/AUTOMQ_ACCESS_KEY/${{ secrets.AUTOMQ_ACCESS_KEY }}/g" "$TF_VAR_FILENAME"
          sed -i "s/AUTOMQ_SECRET_KEY/${{ secrets.AUTOMQ_SECRET_KEY }}/g" "$TF_VAR_FILENAME"
        env:
          TF_BACKEND_BUCKET: ${{ secrets.TF_BACKEND_BUCKET }}
          TF_BACKEND_KEY: ${{ secrets.TF_BACKEND_KEY }}
          TF_FILENAME: ${{ secrets.TF_FILENAME }}
          TF_VAR_FILENAME: ${{ secrets.TF_VAR_FILENAME }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AUTOMQ_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AUTOMQ_SECRET_KEY }}
          aws-region: ${{ inputs.region }}

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/automq_aws
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/automq_aws.pub
          chmod 600 ~/.ssh/automq_aws
          chmod 644 ~/.ssh/automq_aws.pub

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize terraform
        working-directory: driver-automq/deploy/terraform-aws
        run: terraform init

      - name: Terraform Plan
        working-directory: driver-automq/deploy/terraform-aws
        run: terraform plan --auto-approve -var-file terraform-aws-cn.tfvars

      - name: Apply terraform
        working-directory: driver-automq/deploy/terraform-aws
        run: terraform apply --auto-approve -var-file terraform-aws-cn.tfvars

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install --user ansible
          python -m pip install --user jmespath


      - name: Execute Benchmark
        working-directory: driver-automq/deploy/terraform-aws
        run: |
          ansible-playbook deploy.yaml -i terraform-aws/hosts.ini
          ssh -i ~/.ssh/automq_aws $(terraform output --raw user)@$(terraform output --raw client_ssh_host) "cd /opt/benchmark && ./bin/benchmark -d ./driver-automq-for-kafka/driver.yaml ./driver-automq-for-kafka/workloads/fast-tail-read-500m.yaml"
          scp -i ~/.ssh/automq_aws $(terraform output --raw user)@$(terraform output --raw client_ssh_host):/opt/benchmark/*.json /tmp
      - name: Output Benchmark Result
        run: |
          JSON_FILE=$(ls /tmp/*.json)
          cat "${JSON_FILE}"

      - name: Generate Report in Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue_number = 2;
            const markdownReport = `
              ## Issue Report
              Hello, this is example report!!!
            
              We will review it soon. 🚀
            `;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: markdownReport
            });