name: Prepare Streaming Cluster

on:
  workflow_dispatch:
    inputs:
      cloud_provider:
        default: aws-cn
        required: true
        type: string
      compared_streaming_provider:
        default: kafka
        required: true
        type: string
      region:
        default: cn-northwest-1
        required: true
        type: string
      uninstall:
        default: false
        required: true
        type: boolean
      execute_benchmark:
        default: false
        required: true
        type: boolean

jobs:

  prepare_automq_env:
    name: Prepare AutoMQ Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Benchmark Code
        uses: actions/checkout@v3
      - name: Execute Shared Steps
        uses: ./.github/actions/prepare-vs-shared
        with:
          automq_envid: automq
          stream_provider: ${{ inputs.compared_streaming_provider }}
          automq_access_key: ${{ secrets.AUTOMQ_ACCESS_KEY }}
          automq_secret_key: ${{ secrets.AUTOMQ_SECRET_KEY }}
          tf_backend_bucket: ${{ secrets.TF_BACKEND_BUCKET }}
          tf_backend_key: ${{ secrets.TF_BACKEND_KEY }}-${{ inputs.cloud_provider }}
          region: ${{ inputs.region }}
          cloud_provider: ${{ inputs.cloud_provider }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          infra_cost_api_key: ${{ secrets.INFRA_COST_API_KEY }}
          uninstall: ${{ inputs.uninstall }}
          execute_benchmark: ${{ inputs.execute_benchmark }}


  prepare_kafka_env:
    name: Prepare Kafka Environment
    runs-on: ubuntu-latest
    if: ${{ inputs.compared_streaming_provider == 'kafka' }}
    steps:
      - name: Test Workflow
        run: echo "Hello World"
    ## todo support other compare streaming provider



  generate_report:
    name: Generate Report
    runs-on: ubuntu-latest
    needs: [ prepare_automq_env, prepare_kafka_env ]
    steps:
      - name: Generate Report in Issue
        if: ${{ inputs.execute_benchmark }}
        env:
          JSON_FILE_PATH: /tmp
          EXTRACTED_DATA_PATH: /tmp/extracted_data
          BASELINE_COST: ${{ steps.extract_costs.outputs.baseline_cost }}
          USAGE_COST: ${{ steps.extract_costs.outputs.usage_cost }}
          TOTAL_COST: ${{ steps.extract_costs.outputs.total_cost }}
        run: |
          node $GITHUB_WORKSPACE/workflow_scripts/generate_report.js