name: w2

on:
  workflow_run:
    workflows: ["Prepare Streaming Cluster [Install]"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      cloud_provider:
        default: aws-cn
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success'}}
    steps:
      - name: Run a one-line script
        run: echo Hello, world!