name: w2

on:
  workflow_run:
    workflows: ["Prepare Streaming Cluster [Install]"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      cloud_provider:
        default: aws-cn
        required: true
        type: string



jobs:
  get_workflow_conclusion:
    name: Lookup Conclusion of Workflow_Run Event
    runs-on: ubuntu-latest
    outputs:
      conclusion: ${{ fromJson(steps.get_conclusion.outputs.data).conclusion }}
    steps:
      - name: Get Workflow Run
        uses: octokit/request-action@v2.1.0
        id: get_conclusion
        with:
          route: GET /repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    if: ${{ needs.get_workflow_conclusion.outputs.conclusion == 'success' }}
    steps:
      - name: Run a one-line script
        run: echo Hello, world!