name: w2

on:
  workflow_run:
    workflows: [w1]
    types:
      - completed
  schedule:
    - cron: '27 3 * * *'
  workflow_dispatch:
    inputs:
      cloud_provider:
        default: aws-cn
        required: true
        type: string



jobs:
  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Run a one-line script
        run: echo Hello, world!